schedules:
- cron: "0 3 * * Mon"
  displayName: Weekly build
  branches:
    include:
    - master
  always: true

jobs:
- job: 'ParallelTesting'
  pool:
    vmImage: 'windows-latest'
  strategy:
    parallel: 5
  displayName: Run tests in parallel

  steps:
  - task: VSTest@3
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\bin\**\*test.dll
        **\bin\**\*tests.dll
      searchFolder: '$(System.DefaultWorkingDirectory)'
      runOnlyImpactedTests: true
      runAllTestsAfterXBuilds: '3'

  - script: echo Hello, world!